### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pheianox** [xania/view#1]
Hi, you're library looks interesting.

We would be really grateful if you could add some docs for a quick start

**Comment by rubenaprikyan** [comment]
The same is here

**Comment by rubenaprikyan** [comment]
@xania thanks ! Could you please share a simple example of usage before documentations will be written?

**Comment by xania** [comment]
I have a link to a couple of simple examples at:
https://github.com/xania/app-components/tree/main/src/kitchen-sink

Please take a look and let me know if that's of any help

**Comment by pheianox** [comment]
Thanks it helped a lot!
