### ISSUE TITLE
website navigation is broken

### ISSUE THREAD

**Issue by bigmistqke** [xania/view#23]
every link i click in the sidebar leads me back to homepage.
i am on ios (m1) firefox.

**Comment by bigmistqke** [comment]
todos' delete and filtering is broken in demo

**Comment by xania** [comment]
> every link i click in the sidebar leads me back to homepage.

It was broken for a moment while I was upgrading to new version of xania, is it still though? are you referring to app created with `npm create xania`?

PS love ur username :)

**Comment by bigmistqke** [comment]
I am referring to https://xania.github.io/ 

'every link' is incorrect of me though, the links under case study are working, but the links under integration/architecture are leading me back to https://xania.github.io/en/introduction/ 
The same for the links in the reference-tab (components/router). 

PS hihi thank u! xania looks really cool btw!

**Comment by xania** [comment]
> every link' is incorrect of me though, the links under case study are working, but the links under integration/architecture are

That's correct, documentation is still in progress, broken links are there as a reminder. I just finished big refactoring of the reactivity system of xania (I borrowed some concept from Elm). As soon as all demo's and example code are upgraded and working correctly I will dive into docs.

PS thanx

**Comment by xania** [comment]
@bigmistqke btw if you have a specific question just raise an issue and I will try to answer that while docs are still work in progress
