### ISSUE TITLE
initial meeting with Xania may fail to meet expectations.

### ISSUE THREAD

**Issue by paganaye** [xania/view#24]
I typed as instructed

`npm create xania`

it replied

```
Need to install the following packages:
  create-xania@0.1.95
Ok to proceed? (y) 
...
ReferenceError: fetch is not defined
    at $b (/home/pascal/.npm/_npx/2d8987a4ba59c846/node_modules/create-xania/dist/cli.cjs:31:2390)

```

I know it is was because my version of node was too low but it'd be better to actively check the version and display a proper message, wouldn't it?

**Comment by xania** [comment]
> ReferenceError: fetch is not defined

what node version are you using? fetch may not exists in older versions of node. probably will need to polyfill this in `xania-create` package.

**Comment by xania** [comment]
Could you please try running `npm create xania` again. but beware you first have to _uninstall_ the old version manually. 

use one of the commands depending on you OS
- $ npx rimraf ~/.npm/_npx/
- npx rimraf %LocalAppData%\npm-cache_npx

**Comment by xania** [comment]
I don't know if there is a better cli 'framework' that I should use to streamline `npm create '...'`, this has currently a lot of issues, I havent found (yet) an easy way to update installed package that works across all version of node. 

that's probably why a lot of other cli's instructs installing via the g flag. `npm install -g cli` and I should probably do the same, I will need to investigate this approach to be sure but it sound like a solution
